### ISSUE TITLE
automigrate fails if the table doesn't exist

### ISSUE THREAD

**Issue by doginthehat** [mrbatista/loopback-connector-arangodb#28]
I'm just trying out the connector and noticed an error when trying to run automigrate.

I've got a new collection that hasn't been created in the arango database. The automigrate script throws an error saying the collection doesn't exist (which defeats the purpose a bit).

I've narrowed it down to the callback to `collection.drop` 

```
      return collection.drop(function(err) {
        if (err) {
          if (err.response.body != null) {
            err = err.response.body;
            if (!(err.error === true && err.errorNum === 1203 && err.errorMessage === 'unknown collection \'' + model + '\'')) {
                return modelCallback(err);
            }
          }
        }
        debug('create collection %s for model %s', collectionName, model);
        return collection.create(modelCallback);
      });
```

I'm not sure if there's a reason behind having this but taking out the `if (err)` section fixes the first migration problem.

**Comment by mrbatista** [comment]
@doginthehat Sorry for the long delay... It's possible to have fork of repository that reproduce the issue?

Thanks

**Comment by doginthehat** [comment]
@mrbatista That was part of an experimentation test project I had at the time. 

From top my head it was fairly basic, add model > run an automigrate server boot script > error.

I'm guessing it's because it tries to drop the collection even if it doesn't exist.. probably needs to check existence before dropping.

I could try to put a test together, but not sure when I'll get to it.
