### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by jimmyjamieson** [mrbatista/loopback-connector-arangodb#29]
Hey. I'm trying to test this connector out, but I'm getting the following error. 

 "error": {
    "statusCode": 401,
    "name": "TypeError",
    "message": "Converting circular structure to JSON",
  }

Would you know what the issue could be? I don't get it with the memory or mongodb adapter, so I'm guessing it's specific to this.

**Comment by mrbatista** [comment]
@jimmyjamieson please add full stack trace and the dependencies installed for the connector. Thanks

**Comment by jimmyjamieson** [comment]
Hi, 

{
  "name": "test",
  "version": "1.0.0",
  "main": "server/server.js",
  "scripts": {
    "start": "node .",
    "pretest": "eslint .",
    "posttest": "nsp check"
  },
  "dependencies": {
    "arango": "^1.3.4",
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^1.3.0",
    "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.4.0",
    "loopback-connector-arangodb": "github:nvdnkpr/loopback-connector-arangodb",
    "loopback-connector-mongodb": "^1.15.2",
    "loopback-datasource-juggler": "^2.39.0",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^1.0.1"
  },
  "devDependencies": {
    "eslint": "^2.5.3",
    "nsp": "^2.1.0"
  },
  "repository": {
    "type": "",
    "url": ""
  },
  "license": "UNLICENSED",
  "description": "test"
}

Error:

Web server listening at: http://localhost:8000
Browse your REST API at http://localhost:8000/explorer
Unhandled error for request GET /api/v1/Classifieds: TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at stringify (C:\Projects\test\server\node_modules\express\lib\response.js:1064:12)
    at ServerResponse.json (C:\Projects\test\server\node_modules\express\lib\response.js:243:14)
    at ServerResponse.send (C:\Projects\test\server\node_modules\express\lib\response.js:152:21)
    at defaultHandler (C:\Projects\test\server\node_modules\strong-remoting\lib\rest-adapter.js:391:11)
    at restErrorHandler (C:\Projects\test\server\node_modules\strong-remoting\lib\rest-adapter.js:361:14)
    at Layer.handle_error (C:\Projects\test\server\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Projects\test\server\node_modules\express\lib\router\index.js:310:13)
    at C:\Projects\test\server\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Projects\test\server\node_modules\express\lib\router\index.js:330:12)

**Comment by mrbatista** [comment]
1. Run command `npm ls` and paste output 
1. Remove `arango` dependency. This is old javascript driver for ArangoDB. See [README](https://github.com/triAGENS/ArangoDB-JavaScript#arangodb-client)
2. Remove `loopback-connector-arangodb` from dependency.
3. Delete node_modules directory in your project
4. Run command `npm install` loopback-connector-arangodb --save
5. Run command `npm install` in your project
6. Run command `npm ls` and paste output
7. Verify if problem is resolved

**Comment by jimmyjamieson** [comment]
Ok cheers. Will give it a shot :)

**Comment by reidlai** [comment]
After using Node 7 debugger, I found the following info:

debug> breakOnException
exception in node_modules/body-parser/lib/types/json.js:158
TypeError: Cannot read property 'toLowerCase' of undefined
 156 function getCharset (req) {
 157   try {
>158     return contentType.parse(req).parameters.charset.toLowerCase()
 159   } catch (e) {
 160     return undefined

**Comment by reidlai** [comment]
Using NodeJS 7 debugger, I found the following: 

< Web server listening at: http://0.0.0.0:3000
< Browse your REST API at http://0.0.0.0:3000/explorer
debug> breakOnException
exception in node_modules/body-parser/lib/types/json.js:158
TypeError: Cannot read property 'toLowerCase' of undefined
 156 function getCharset (req) {
 157   try {
>158     return contentType.parse(req).parameters.charset.toLowerCase()
 159   } catch (e) {
 160     return undefined
debug> next
break in node_modules/body-parser/lib/types/json.js:160
 158     return contentType.parse(req).parameters.charset.toLowerCase()
 159   } catch (e) {
>160     return undefined
 161   }
 162 }
next
break in node_modules/body-parser/lib/types/json.js:162
 160     return undefined
 161   }
>162 }
 163 
 164 /**
cont
exception in node_modules/express/lib/response.js:1064
TypeError: Converting circular structure to JSON
 1062   return replacer || spaces
 1063     ? JSON.stringify(value, replacer, spaces)
>1064     : JSON.stringify(value);
 1065 }
 1066

**Comment by mrbatista** [comment]
@reidlai  at the moment node V7 is not supported. We are going  to add support for node V4 and V6 shortly.

**Comment by reidlai** [comment]
@mrbatista same in Node 6 so I use Node 7 debugger to trace. I'll fork your
repo and trace it :)

**Comment by reidlai** [comment]
@mrbatista, I got the reason.  "TypeError: Converting circular structure to JSON" will happen when loopback cannot find model in ArangoDB.  Is there any same feature like loopback-connector-mongodb with automatic model creation?
