### ISSUE TITLE
Add support to ArangoDB 3.x

### ISSUE THREAD

**Issue by mrbatista** [mrbatista/loopback-connector-arangodb#35]

**Comment by smith64fx** [comment]
No support for ArangoDB 3.x? Is this project here dead?

**Comment by smith64fx** [comment]
Something like client.save() doesn't work.

I get:
```
(node:47833) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error updateOrCreate not supported for version 3.0.0
```

**Comment by mrbatista** [comment]
@smith64fx  driver is not "production ready" for ArangoDB 3.0.0

**Comment by smith64fx** [comment]
@mrbatista ok no problem. If there are problems, I can also help you. 
Really happy to see you work with coffee script :)

Do you have something like an issue list regarding 3.0? 
Until now I had no problems at all using 3.0

**Comment by smith64fx** [comment]
I made a fork to develop 3.* compatibility.
https://github.com/schmidigital/loopback-connector-arangodb/

Thanks @mrbatista for this awesome work. Let's get to 3.*!

**Comment by mrbatista** [comment]
@smith64fx  Any PRs are welcome! :)

**Comment by smith64fx** [comment]
@mrbatista long time passed..

Can we create a v3 branch/tag? Or what is best practice for it..
I don't wanna break the other people's environment with the update.

**Comment by mrbatista** [comment]
Version 2.0.0 add support to ArangoDB 3.x.x. 🎉

**Comment by smith64fx** [comment]
@mrbatista Thanks, awesome :)
