### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by smith64fx** [mrbatista/loopback-connector-arangodb#37]
Hey guys,
First of all. Thanks for this great work! I runned your example and it worked. (Even if I thought, it will not work because of #35)

We are planning to create a large platform and will expect a lot of simultaneous users on the site. (About 10.000 at the same time for the beginning)

My question now: Is Loopback + ArangoDB production ready or is there something to consider or still to do? We really like to use Loopback, because it has so many awesome things starting with the nice Web UI :-) (before we used SailsJS)

Thank you!

**Comment by mrbatista** [comment]
@smith64fx the project is not dead. I will soon add support to ArangoDB 3.xx. Stay tuned!
Now the project is production ready for ArangoDB v2.8

**Comment by smith64fx** [comment]
Ah ok cool :)
Thank you for this great work!

I tried the examples and they work. That means it is possible to use the connector but you have to implement new features that came with 3.xx?
