### ISSUE TITLE
Return also "_id" after creating model

### ISSUE THREAD

**Issue by smith64fx** [mrbatista/loopback-connector-arangodb#38]
Hi @mrbatista 

In this commit I removed 3 lines in the "find" method so I also get back the "_id" property, which is often important for creating edges.

https://github.com/schmidigital/loopback-connector-arangodb/commit/d7d14f81517e736ddd4cbb0df5337743ce85884c

Now I'm trying to do the same in the "create" function.
But as far as i can see, I cannot manipulate the data inside the "create" function.

Line 332
```
      if isEdge
        data[fromName] = result._from if fromName isnt '_from'
        data[toName] = result._to if toName isnt '_to'

      if fullIdName
        data[fullIdName] = fullIdValue

      callback err, idValue
```

These lines should manipulate the data and add _from, _to and _id, but they don't. And in the callback only the idValue is given back which is then inserted as "id" property of the new instance.

So...... How can we actually manipulate the data after creating it? Do you have any idea?

Many thanks for this good work!

**Comment by smith64fx** [comment]
as i can see, there is already an issue :)

https://github.com/strongloop/loopback-datasource-juggler/issues/442

**Comment by mrbatista** [comment]
@smith64fx  sede https://github.com/mrbatista/loopback-connector-arangodb/blob/f2912c4392dd1ee9c47591b3527652c140c315ca/test/crud/edge.test.coffee#L23

**Comment by mrbatista** [comment]
@smith64fx Add option `updateOnLoad: true` in our json model file. Now you have a property `_id`. I will add this configuration in the README. The same applies for ArangoDB document.

**Comment by smith64fx** [comment]
![image](https://cloud.githubusercontent.com/assets/3246782/21222112/99573104-c2c0-11e6-8cd2-c95274d4afb5.png)

Works like charm! 
Gracie! Now I don't have to use a forked juggler anymore.
