### ISSUE TITLE
run AQL in remote method

### ISSUE THREAD

**Issue by reidlaiatags** [mrbatista/loopback-connector-arangodb#39]
Any example to show how to run AQL in loopback remote method?

**Comment by mrbatista** [comment]
@reidlaiatags See https://github.com/mrbatista/loopback-connector-arangodb/blob/master/test/core.test.coffee#L190

**Comment by mrbatista** [comment]
@codeyad I am closing the issue as resolved. If the issue is still persisting, please fell free to leave a comment and I will re-open the issue. Thanks.

**Comment by mrbatista** [comment]
@reidlaiatags I am closing the issue as resolved. If the issue is still persisting, please fell free to leave a comment and I will re-open the issue. Thanks.
