### ISSUE TITLE
Add compatibilities with arangodb 3.3

### ISSUE THREAD

**Issue by mrbatista** [mrbatista/loopback-connector-arangodb#74]

**Comment by mrbatista** [comment]
closed via #79

**Comment by Gby56** [comment]
Is it published on npm ? because after install the coffeescript is the same and still throws unknown collection instead of collection not found

**Comment by mrbatista** [comment]
@Gby56 sorry wrong release. Updated to 2.1.1 fix the problem.

**Comment by Gby56** [comment]
Hey by the way, I'm trying to use the autoupdate, it seems that the request for the index creation is malformed, the details might be wrong
Error is here :
https://github.com/mrbatista/loopback-connector-arangodb/blob/master/src/arangodb.coffee#L927

I went into arangojs but couldn't find a fix, the parameter index.options is interpreted as a callback, and throws TypeError: callback is not a function in /arangojs/lib/collection.js:573

**Comment by mrbatista** [comment]
@Gby56 See #10
