### ISSUE TITLE
Automigration not creating collection

### ISSUE THREAD

**Issue by Gby56** [mrbatista/loopback-connector-arangodb#76]
Hi,
I think this might be a version incompatibility, I'm using arangodb 3.3.8, it might come from arangojs version (yours is 5.0.0, latest is 6.2.4)

I get this error : `ArangoError: collection not found`
Error code 1203, code 404

Apparently in arangodb.js:1350, it tries to drop the collection first, then create it, so of course it's going to fail...

Any ideas ?

**Comment by Gby56** [comment]
The error message probably changed on this version of ArangoDB, line 1353 should be 
`if (!(err.error === true && err.errorNum === 1203 && err.errorMessage === 'collection not found')) {`

**Comment by mrbatista** [comment]
@Gby56 Added support for arangodb 3.3! Please install version 2.1.0
